# https://kubernetes.io/docs/concepts/configuration/secret/
{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "insights-beta.name" }}
  namespace: default
type: Opaque
data:
  {{- with .Values.secrets.data -}}
    {{- toYaml . | nindent 2 -}}
  {{ - end }}
{{- end -}}